# Generated by Django 5.2 on 2025-04-10 00:44
# This migration is for the PathId model used by the DAG package.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="PathId",
            fields=[
                (
                    "content_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="contenttypes.contenttype",
                    ),
                ),
                ("value", models.IntegerField()),
            ],
        ),
    ]
