# Generated by Django 5.0.4 on 2024-11-21 22:31

import django.db.models.deletion
from django.db import migrations, models
from apps.dag.models import DAGEntity


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MockEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            bases=(models.Model, DAGEntity),
        ),
        migrations.CreateModel(
            name="MockDAGLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_id", models.IntegerField()),
                ("depth", models.IntegerField()),
                ("weight", models.IntegerField(default=1)),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_child",
                        to="dag_tests.mockentity",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_parent",
                        to="dag_tests.mockentity",
                    ),
                ),
            ],
        ),
    ]
